-- Player ID Mapping
-- Generated by map_player_names.js

-- "Altmaier D." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Altmaier D.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Arnaldi M." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Arnaldi M.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Auger-Aliassime F." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Auger-Aliassime F.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Baez S." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Baez S.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Bernet H." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Bernet H.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Berrettini M." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Berrettini M.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Bertola R." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Bertola R.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Borges N." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Borges N.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Brooksby J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Brooksby J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Bublik A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Bublik A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Budkov Kjaer N." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Budkov Kjaer N.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Cerundolo F." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Cerundolo F.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Cilic M." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Cilic M.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Cobolli F." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Cobolli F.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Collignon R." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Collignon R.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Darderi L." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Darderi L.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Davidovich Fokina A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Davidovich Fokina A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "De Minaur A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('De Minaur A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Diallo G." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Diallo G.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Dzumhur D." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Dzumhur D.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Etcheverry T." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Etcheverry T.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Fearnley J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Fearnley J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Fonseca J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Fonseca J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Fritz T." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Fritz T.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Giron M." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Giron M.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Goffin D." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Goffin D.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Griekspoor T." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Griekspoor T.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Halys Q." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Halys Q.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Humbert U." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Humbert U.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Kecmanovic M." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Kecmanovic M.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Khachanov K." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Khachanov K.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Korda S." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Korda S.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Kovacevic A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Kovacevic A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Lehecka J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Lehecka J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Machac T." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Machac T.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Majchrzak K." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Majchrzak K.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Medjedovic H." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Medjedovic H.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Medvedev D." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Medvedev D.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Mensik J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Mensik J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Michelsen A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Michelsen A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Misolic F." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Misolic F.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Moutet C." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Moutet C.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Mpetshi G." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Mpetshi G.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Muller A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Muller A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Munar J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Munar J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Musetti L." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Musetti L.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Nakashima B." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Nakashima B.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Norrie C." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Norrie C.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Opelka R." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Opelka R.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Popyrin A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Popyrin A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Rodionov J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Rodionov J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Royer V." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Royer V.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Rublev A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Rublev A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Ruud C." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Ruud C.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Shapovalov D." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Shapovalov D.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Shelton B." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Shelton B.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Sinner J." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Sinner J.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Sonego L." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Sonego L.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Tabilo A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Tabilo A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Ugo Carabelli C." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Ugo Carabelli C.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Vacherot V." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Vacherot V.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Van De Zandschulp B." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Van De Zandschulp B.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Wawrinka S." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Wawrinka S.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

-- "Zverev A." → NEW PLAYER - INSERT REQUIRED
-- INSERT INTO players (name, country, birth_date, height, weight, playing_hand)
-- VALUES ('Zverev A.', 'XXX', 'YYYY-MM-DD', 185, 75, 'right');

